from .estaticas import *
from .curso_view import *
from .ppc_view import *
from .motivo_abono_view import *
from .motivo_dispensa_view import *
from .motivo_exercicios_view import *
from .coordenador_view import *
from .aluno_view import *
from .cre_view import *
from .usuario_view import *
from .form_tranc_matricula_view import *
from .anexo_view import *
from .mandato_view import *
