# Generated by Django 5.1.2 on 2025-03-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='id',
        ),
        migrations.AlterField(
            model_name='curso',
            name='codigo',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ppc',
            name='codigo',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
