# Generated by Django 5.0 on 2025-03-30 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_app', '0002_remove_curso_id_alter_curso_codigo_alter_ppc_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoDispensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Digite o motivo da dispensa', max_length=200, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
