# Generated by Django 5.1.7 on 2025-03-30 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_app', '0002_remove_curso_id_alter_curso_codigo_alter_ppc_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoAbono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Descrição')),
                ('tipo_falta', models.CharField(choices=[('Falta Justificada', 'Fj'), ('Falta Abonada', 'Fa')], max_length=20, verbose_name='Tipo de Falta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
