# Generated by Django 5.1.7 on 2025-03-31 04:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_app', '0003_motivodispensa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')])),
                ('telefone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='O telefone deve conter 10 ou 11 dígitos numéricos.', regex='^\\d{10,11}$')])),
                ('data_nascimento', models.DateField()),
                ('siape', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')])),
                ('telefone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='O telefone deve conter 10 ou 11 dígitos numéricos.', regex='^\\d{10,11}$')])),
                ('data_nascimento', models.DateField()),
                ('siape', models.IntegerField(unique=True)),
                ('inicio_mandato', models.DateField()),
                ('fim_mandato', models.DateField(blank=True, null=True)),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes_app.curso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
