# Generated by Django 5.1.7 on 2025-03-31 05:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_app', '0004_cre_coordenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordenador',
            name='cpf',
            field=models.CharField(help_text='Escreva aqui o CPF', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')], verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='data_nascimento',
            field=models.DateField(help_text='Escreva aqui a data de nascimento', verbose_name='Data nascimento:'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='email',
            field=models.EmailField(help_text='Escreva aqui o email', max_length=254, unique=True, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='fim_mandato',
            field=models.DateField(blank=True, help_text='Escreva aqui a data de fim do mandato', null=True, verbose_name='Fim Mandato:'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='inicio_mandato',
            field=models.DateField(help_text='Escreva aqui a data de início do mandato', verbose_name='Inicio Mandato:'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='nome',
            field=models.CharField(help_text='Escreva aqui o nome', max_length=100, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='siape',
            field=models.IntegerField(help_text='Escreva aqui o número do SIAPE.', unique=True, verbose_name='SIAPE:'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='telefone',
            field=models.CharField(help_text='Escreva aqui o telefone', max_length=11, validators=[django.core.validators.RegexValidator(message='O telefone deve conter 10 ou 11 dígitos numéricos.', regex='^\\d{10,11}$')], verbose_name='Telefone:'),
        ),
        migrations.AlterField(
            model_name='cre',
            name='cpf',
            field=models.CharField(help_text='Escreva aqui o CPF', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')], verbose_name='CPF:'),
        ),
        migrations.AlterField(
            model_name='cre',
            name='data_nascimento',
            field=models.DateField(help_text='Escreva aqui a data de nascimento', verbose_name='Data nascimento:'),
        ),
        migrations.AlterField(
            model_name='cre',
            name='email',
            field=models.EmailField(help_text='Escreva aqui o email', max_length=254, unique=True, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='cre',
            name='nome',
            field=models.CharField(help_text='Escreva aqui o nome', max_length=100, verbose_name='Nome:'),
        ),
        migrations.AlterField(
            model_name='cre',
            name='siape',
            field=models.IntegerField(help_text='Escreva aqui o número do SIAPE.', unique=True, verbose_name='SIAPE:'),
        ),
        migrations.AlterField(
            model_name='cre',
            name='telefone',
            field=models.CharField(help_text='Escreva aqui o telefone', max_length=11, validators=[django.core.validators.RegexValidator(message='O telefone deve conter 10 ou 11 dígitos numéricos.', regex='^\\d{10,11}$')], verbose_name='Telefone:'),
        ),
    ]
