# Generated by Django 5.1.7 on 2025-03-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_app', '0005_alter_coordenador_cpf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coordenador',
            options={'ordering': ('nome',), 'verbose_name': 'Coordenador', 'verbose_name_plural': 'Coordenadores'},
        ),
        migrations.AlterModelOptions(
            name='cre',
            options={'ordering': ('nome',), 'verbose_name': 'CRE', 'verbose_name_plural': 'CREs'},
        ),
    ]
