# Generated by Django 5.0 on 2025-04-01 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_app', '0003_motivoabono'),
        ('solicitacoes_app', '0006_alter_coordenador_options_alter_cre_options'),
    ]

    operations = [
    ]
