# Generated by Django 5.0 on 2025-04-01 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_app', '0007_merge_20250401_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoExercicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(help_text='Digite o motivo da dispensa', max_length=200, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='Descrição')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='email',
            field=models.EmailField(help_text='Escreva aqui o email', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='cre',
            name='email',
            field=models.EmailField(help_text='Escreva aqui o email', max_length=254, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email:'),
        ),
    ]
