# Generated by Django 5.0 on 2025-04-01 06:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_app', '0008_motivoexercicios_alter_coordenador_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Escreva aqui o nome', max_length=100, verbose_name='Nome:')),
                ('email', models.EmailField(help_text='Escreva aqui o email', max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Email:')),
                ('cpf', models.CharField(help_text='Escreva aqui o CPF', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')], verbose_name='CPF:')),
                ('telefone', models.CharField(help_text='Escreva aqui o telefone', max_length=11, validators=[django.core.validators.RegexValidator(message='O telefone deve conter 10 ou 11 dígitos numéricos.', regex='^\\d{10,11}$')], verbose_name='Telefone:')),
                ('data_nascimento', models.DateField(help_text='Escreva aqui a data de nascimento', verbose_name='Data nascimento:')),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('turma', models.CharField(max_length=100)),
                ('ano_ingresso', models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2025)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='email',
            field=models.EmailField(help_text='Escreva aqui o email', max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='cre',
            name='email',
            field=models.EmailField(help_text='Escreva aqui o email', max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Email:'),
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Escreva aqui o nome', max_length=100, verbose_name='Nome:')),
                ('email', models.EmailField(help_text='Escreva aqui o email', max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Email:')),
                ('cpf', models.CharField(help_text='Escreva aqui o CPF', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 dígitos numéricos.', regex='^\\d{11}$')], verbose_name='CPF:')),
                ('telefone', models.CharField(help_text='Escreva aqui o telefone', max_length=11, validators=[django.core.validators.RegexValidator(message='O telefone deve conter 10 ou 11 dígitos numéricos.', regex='^\\d{10,11}$')], verbose_name='Telefone:')),
                ('data_nascimento', models.DateField(help_text='Escreva aqui a data de nascimento', verbose_name='Data nascimento:')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitacoes_app.aluno', unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
