# Generated by Django 5.0.3 on 2025-04-01 22:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes_app', '0009_aluno_alter_coordenador_email_alter_cre_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('nome', models.CharField(help_text='Digitar o nome da disciplina:', max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Disciplina')),
                ('codigo', models.CharField(help_text='Digitar o código da disciplina:', max_length=50, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Codigo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
