from .curso import *
from .ppc import *
from .motivo_abono import *
from .tipo_falta import *
from .status import *
from .motivo_dispensa import *
from .motivo_exercicios import *
from .coordenador import *
from .cre import *
from .aluno import *
from .responsavel import *
from .disciplina import *
from .tipo_falta import *
from .turma import *
from .solicitacao import *
from .form_tranc_matricula import *
from .form_dispensa_ed_fisica import *
from .anexo import *
from .form_abono_falta import *
from .status_usuario import *
from .mandato import *
from .form_tranc_disciplina import *
from .forms.form_exercicio_domiciliar import *
from .forms.form_desistencia_vaga import *
from .nome import *
from .posse_solicitacao import *
from .calendario_academico import *
from .periodo_disciplina import *