from .curso import *
from .ppc import *
from .motivo_abono import *
from .tipo_falta import *
from .status import *
from .motivo_dispensa import *
from .motivo_exercicios import *
from .coordenador import *
from .cre import *
from .aluno import *
from .responsavel import *
